server:
  port: 8080
#  servlet-path: /mortgage
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.iwellmass.mortgage.model.dto
spring:
  jmx:
    enabled: false
    default-domain: mortgage
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://10.15.56.142:3306/mortgage?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: Zj2019!12345678
    driverClassName: com.mysql.jdbc.Driver
    druid:
      #2.连接池配置
      #初始化连接池的连接数量 大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      #配置获取连接等待超时的时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      # 是否缓存preparedStatement，也就是PSCache  官方建议MySQL下建议关闭   个人建议如果想用SQL防火墙 建议打开
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filter:
        stat:
          merge-sql: true
          slow-sql-millis: 5000
      #3.基础监控配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
        #设置不统计哪些URL
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: true
        session-stat-max-count: 100
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        #设置监控页面的登录名和密码
        login-username: admin
        login-password: admin
        allow: 10.15.56.140
        #deny: 192.168.1.100
    tomcat:
      test-on-borrow: true

# 不动产ip地址变量抽取定义
mortgageUrl:
  ipAddress: 172.26.60.235:8092
# 不动产区块链ip地址变量抽取定义
blockChainUrl:
  callbackIpAddress: 19.15.56.146:8080
  getBlockChainIpAddress: 172.26.52.233:10070

# Token校验ip地址变量抽取定义
tokenCheckUrl:
  checkTokenIpAddress: 10.15.56.146:8080

# 公积金ip地址抽取定义
providentUrl:
  providentQueryIpAddress: 192.142.252.243:4604


m2Keys:
  #m2公钥
  myPrivateKey: '187175C672F35FD1965A44D7143DD23E0547EC5319D466E90BBD3875A278CB32'
  #m2公钥
  mortgagePublicKey: '04CA443A2B9A0492EC174E08D4BCC3050ADF669A879FBE5EC9A4D0DF513D460035C5B5BB014D321B01D51EEB4A4A63BF17BE1657E7AF02878C3196511D52448067'
sm4Key:
  #m4对称秘钥
  symmetryKey: 'a319a636dcfe3338140c566a88463bca'

  #区块链相关配置开始
chainm2Keys:
  #区块链m2私钥
  chainPrivateKey: '00E9431C0965B7061E94A671D1C0844A0A1D1230FD0ACD5DF2EDDB2DDA5DBFF9EC'
  #区块链m2公钥
  chainPublicKey: '04714EFE283751DF5FE673E6B84D759D013DB11864FD709447CD0C3B436D3EBFDAC7A517BB6639DEEA3D469F29EFEF95CD5922D61C9B3D129F28F5BD71BE7D7DA2'
  #国密规范测试用户ID
  userId: 1234567812345678
  #区块链其他私钥
  otherPrivKey: ''
chainurl:
  callbackUrl: 'http://${blockChainUrl.callbackIpAddress}/cbirc/api/immovables/NotifyBlockchainStatus'
  getBlockchainUrl: 'http://${blockChainUrl.getBlockChainIpAddress}/prepose/circ/bizLog/save'
  #区块链相关配置结束

certificate:
  #电子证照查询时间间隔
  intervaltime: 15
debug: false
logging:
  level:
    com.iwellmass.mortgage.dao: debug
mortgage:
  #NFS根目录
  fileRootDir: /data
  #不动产状态查询应用id
  queryAppId: 'A00001'
  #撤销业务id
  cancelApplyId: 'A00001'
  #不动产解押查询应用id
  unMortgageQueryAppId: 'A00001'
  #不动产解押录入应用id
  unMortgageApplyAppId: 'A00001'
  #文件删除应用id
  deleteFileId: 'A00002'
  #电子证照应用id
  certificateAppId: 'A00003'
  #IP解密秘钥
  userIpkeyStr: 'CZ5U/ZP5+vMU9orbS+KYEw=='
  #不动产状态查询接口地址
  queryMortgageStatusUrl: 'http://${mortgageUrl.ipAddress}/estateShare/cbrc/getRightByCertNo'
  #不动产抵押前查询接口地址
  queryMortgageInfoUrl: 'http://${mortgageUrl.ipAddress}/estateShare/cbrc/getMortgageInfo'
  #不动产抵押信息录入接口地址
  saveMortgageUrl: 'http://${mortgageUrl.ipAddress}/estateShare/cbrc/saveMortgage'

  #抵押进度查询接口地址
  queryMortgageProgressUrl: 'http://${mortgageUrl.ipAddress}/estateShare/cbrc/queryStep'
  #TOKEN校验接口地址
  mortgageCheckTokenUrl: 'http://${tokenCheckUrl.checkTokenIpAddress}/cbirc/auth/checkToken'
  #纸质文件材料移交接口地址
  fileTransferUrl: 'http://${mortgageUrl.ipAddress}/estateShare/cbrc/bizTransfer'
  #解押前查询接口地址
  unMortgageQueryUrl: 'http://${mortgageUrl.ipAddress}/estateShare/cbrc/getCancelMortgageInfo'
  #解押录入申请接口地址
  unMortgageApplyUrl: 'http://${mortgageUrl.ipAddress}/estateShare/cbrc/saveCancelMortgage'
  #电子证照接口地址
  electronicCertificateUrl: 'http://${mortgageUrl.ipAddress}/estateShare/cbrc/getCert'
  #撤销业务接口地址
  cancelApplyUrl: 'http://${mortgageUrl.ipAddress}/estateShare/cbrc/bizCancel'
  #业务提交接口地址
  bizSubmitUrl: 'http://${mortgageUrl.ipAddress}/estateShare/cbrc/bizComplete'
  #不动产抵押信息更新录入接口地址
  updateMortgageUrl: 'http://${mortgageUrl.ipAddress}/estateShare/cbrc/updateMortgage'
  #解押录入更新申请接口地址
  updateUnMortgageApplyUrl: 'http://${mortgageUrl.ipAddress}/estateShare/cbrc/updateCancelMortgage'
  #文件附件删除地址
  deleteFileUrl: 'http://${mortgageUrl.ipAddress}/estateShare/cbrc/uploadFile'

provident:
  publicKey: '0411A6FCC5F69BA9A0C35D50C4162F3D821248D7ECE30219463BC139CAAA4AE8DF73CF2508353DC939802C2FF812DBAD8629CEC193C91F7CF8EA1EC5DCA5131FD5'
  privateKey: '00DB077661AA3FD4C4CB5BBD8F6A4C32097B217D63487867C6F1D9AF235B1B3619'
  appId: 'A00001'
  username: 'ybj'
  password: '123'
  #个人公积金查询地址
  providentQueryUrl: 'http://${providentUrl.providentQueryIpAddress}/grdk/ybjgl/syyh9017.action'
  #企业公积金查询地址
  entProvidentQueryUrl: 'http://192.142.252.243:4600/gjj/ybjcxgl/syyhdwjcxx.action'
  #个人公积金查询入库开关 0-关 1-开
  bankSwitcher: 1
  providentSwitcher: 0
  #企业公积金缴存查询入库开关
  bankEntSwitcher: 1
  entProvidentSwitcher: 1

civil:
  bankSwitcher: 1
  civilSwitcher: 0
  civilQueryUrl: 'http://192.166.151.57/datacenter/common/api/getData'
  token:
    cremation: 'OWNlZTc5ODI0OWZiNGQxOTg5ZGUwMDkwYjg4YzNjMTU7ZjZiMjgzNzUzZjRhNGQ2MGIyMDMwMDA2YWUyODM2ZjA7YjVmZjRkM2U2ZjljNDJjMWFhMDZiNGYzNTBmMzcwMDA7NmQyNjdiNzE5ZDkxNDEzYmFkN2JmNTc5YTFjMzBmZDY='
    assistance: 'NDAzZDg2MTU5YTczNDQwZWEwNTIxMzU2YWM3MDFjODg7MzgyYWU2NTlkMGUxNDI2YWI0NjAzZjk1MWRhMGUyNDg7NzAyNzAxMjQ2MDU0NDljMDg4ODIxYmFlZTg4ODM3YzY7NjczNGRhOTE5YTFmNDNmYmJmNTIyNjBkZTc0ZTg2OWU='
    marriage: 'YTM4NjI4NGQ4ZDk0NDJjYWFmNGYzZTNkZDEwM2FhY2U7YTJmYzYxYTI1MjdjNDhkZWFkZTNlOWNkMDA5NWFiMjc7ODczYjA4MTBmNTc0NGM3NGIwOTJiNDQyNzdmNGVlYzE7MzBiMGIwYjM0ZjkxNDU4MmIxNTQzMjcxYjg2MzMzY2E='


